apiVersion: apps/v1
kind: Deployment
metadata:
  name: "${BUILD_TIMESTAMP_DEPLOYMENT}"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-container
          image: "${IMAGE_NAME}:${BUILD_TIMESTAMP_DEPLOYMENT}"
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1